siteTitle = 'Phong Cách Ăn'
siteDescr = 'Tân trang homestay'
siteDescription = "Tôi Phạm Xuân Tiếp, tổng hợp những món đồ mà mình cần trong cuộc sống và công việc để khi đủ tiền thì rinh món đồ đó về nhà"
siteUrl = "https://techdsi.com"
siteBandcampUrl = 'https://techdsi.com'
siteMenuOne = 'Bữa Ăn'
siteMenuTwo = 'Món Ngon'
siteMenuThree = 'Quan tâm'
siteAddress = 'Ấp Bãi Vòng, Xã Hàm Ninh, Thành phố Phú Quốc'
siteAddress2 = 'Tỉnh Kiên Giang, Việt Nam. Postal code 920000'
sitePhone = '0899150055'
sitePhoneLink = 'tel:+84-089-915-0055'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/OdayakaPhuQuoc'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/OdayakaPhuQuoc'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com'
siteYoutubeUrl = 'https://www.youtube.com/channel/UC2xhVmkOYPKibhJm3f0f3hw'

linkPrefix = '/'
